# Extract PII from an LM

dataset_args:
  dataset_path: ../src/pii_leakage/extern/echr
  dataset_mode: undefended
  sample_duplication_rate: 1

trainer_args:
  save_steps: 10000
  callback_after_n_steps: 10000
  limit_eval_dataset: 100
  num_train_epochs: 4
  gradient_accumulation_steps: 4
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4

model_args:
  architecture: gpt2
  pre_trained: False
  model_ckpt: # Edit this path to try your own model.

ner_args:
  ner: flair
  ner_model: flair/ner-english-ontonotes-large
  anon_token: <MASK>
  anonymize: False

outdir_args:
  root: # Edit this path to save the pretrained model.